### ISSUE TITLE
Mapfactor Crashes, but only when running under Centrafuse 4.4.9

### ISSUE THREAD

**Issue by myurkoski** [johnjore/Centrafuse-MapFactor-Navigator#1]
I encounter frequent crashes running mapfactor 18 under this plugin within CF 4.4.9. When I just launch mapfactor by itself, it seems far more stable. Has anything change since this was released under Navigator 14 that would cause 18 to be less stable within this plugin? Same issues existed in 4.4.7 as well.

**Comment by johnjore** [comment]
Not enough information regarding "crashes" to provide anything solid. 

For difference between nav14 and 18, best to ask mapfactor. 

Crashes are "probably" not related to cf version or cf plugin. Suspect resource issue (out of memory or bad memory etc). 

Start cf w plugin disabled, minimise cf and launch navigator. If crashes occur, not related to cf or cf plugin and need fixing first. (memory etc) 

When this is 100% stable, then try using plugin again.

**Comment by myurkoski** [comment]
Closing as resolved per your input
